### ISSUE TITLE
Bad TTFP and crashing Felix in KDD scale/churn test

### ISSUE THREAD

**Issue by lwr20** [projectcalico/libcalico-go#669] opened 2017-11-10 13:41 UTC
I'm running a 10 node scale/churn test.  Same setup as ET's etcd rig.
99%ile is bad:
```
$ ./stats.sh 
Total pod reports=5128
99% quantile TTFP=12.921837768554582
50% quantile TTFP=0.007270455360412598
```
calico-node logs show that Felix is cyclically crashing:

 ```
...
2017-11-10 13:34:52.200 [INFO][3160] int_dataplane.go 705: Finished applying updates to dataplane. msecToApply=1.362935
2017-11-10 13:34:52.815 [INFO][3160] watcher.go 124: Watch event indicates a terminated watcher resource="NetworkPolicy (custom)"
2017-11-10 13:34:52.815 [INFO][3160] watcher.go 85: Watcher process terminated resource="NetworkPolicy (custom)"
2017-11-10 13:34:52.815 [ERROR][3160] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:34:52.816 [INFO][3160] networkpolicy.go 395: Watcher process terminated
2017-11-10 13:34:52.816 [INFO][3160] watchercache.go 86: Watch channel closed by remote - recreate watcher ListRoot="/calico/resources/v2/projectcalico.org/networkpolicies"
2017-11-10 13:34:52.816 [INFO][3160] watchercache.go 126: Starting watch sync/resync processing ListRoot="/calico/resources/v2/projectcalico.org/networkpolicies"
2017-11-10 13:34:52.816 [INFO][3160] watchercache.go 128: Stopping previous watcher ListRoot="/calico/resources/v2/projectcalico.org/networkpolicies"
2017-11-10 13:34:52.816 [INFO][3160] watcher.go 133: Process watcher done event in kdd client resource="NetworkPolicy (namespaced)"
2017-11-10 13:34:52.816 [INFO][3160] networkpolicy.go 305: Watching two resources at individual revisions crdNPRev="195517" k8sNPRev="195520"
2017-11-10 13:34:52.816 [INFO][3160] watcher.go 85: Watcher process terminated resource="NetworkPolicy (namespaced)"
2017-11-10 13:34:52.817 [INFO][3160] watcher.go 83: Watcher process started resource="NetworkPolicy (namespaced)"
2017-11-10 13:34:52.818 [INFO][3160] watcher.go 83: Watcher process started resource="NetworkPolicy (custom)"
2017-11-10 13:34:52.818 [FATAL][3160] watchercache.go 117: Unknown event type received from the datastore EventType="" ListRoot="/calico/resources/v2/projectcalico.org/networkpolic
ies"
2017-11-10 13:34:52.818 [INFO][3160] networkpolicy.go 393: Watcher process started
2017-11-10 13:34:52.891 [INFO][3273] logutils.go 83: Early screen log level set to info
2017-11-10 13:34:52.894 [INFO][3273] felix.go 144: Felix starting up GOMAXPROCS=32 buildDate="2017-11-10T08:00:33+0000" gitCommit="7903adf86737a3654660986bc9017bb30ce9f41a" version
="3.0.0-alpha1-38-g7903adf8"
2017-11-10 13:34:52.894 [INFO][3273] felix.go 145: Command line arguments: map[--config-file:/etc/calico/felix.cfg --version:false]
2017-11-10 13:34:52.894 [INFO][3273] felix.go 150: Loading configuration...```
...
```

**Comment by lwr20** [comment] 2017-11-10 13:42
Crash seems to be every couple of minutes.
```
$ kubectl logs -n kube-system calico-node-9qt4f calico-node | grep ERROR
2017-11-10 12:50:20.427 [ERROR][9] customresource.go 128: Error updating resource Key=FelixConfiguration(default) Name="default" Resource="FelixConfigurations" Value=&v2.FelixConfiguration{TypeMeta:v1.TypeMeta{Kind:"FelixConfiguration", APIVersion:"projectcalico.org/v2"}, ObjectMeta:v1.ObjectMeta{Name:"default", GenerateName:"", Namespace:"", SelfLink:"", UID:"b5c195f2-c615-11e7-b31c-42010a80002a", ResourceVersion:"4218", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:63645915020, nsec:0, loc:(*time.Location)(0x1cb3c00)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v2.FelixConfigurationSpec{UseInternalDataplaneDriver:(*bool)(nil), DataplaneDriver:"", IPv6Support:(*bool)(nil), IgnoreLooseRPF:(*bool)(nil), RouteRefreshIntervalSecs:(*int)(nil), IptablesRefreshIntervalSecs:(*int)(nil), IptablesPostWriteCheckIntervalSecs:(*int)(nil), IptablesLockFilePath:"", IptablesLockTimeoutSecs:(*int)(nil), IptablesLockProbeIntervalMillis:(*int)(nil), IpsetsRefreshIntervalSecs:(*int)(nil), MaxIpsetSize:(*int)(nil), NetlinkTimeoutSecs:(*int)(nil), MetadataAddr:"", MetadataPort:(*int)(nil), InterfacePrefix:"", ChainInsertMode:"", DefaultEndpointToHostAction:"", IptablesFilterAllowAction:"", IptablesMangleAllowAction:"", LogPrefix:"", LogFilePath:"", LogSeverityFile:"", LogSeverityScreen:"info", LogSeveritySys:"", IPIPEnabled:(*bool)(0xc420349cd8), IPIPMTU:(*int)(nil), ReportingIntervalSecs:(*int)(0xc420349d68), ReportingTTLSecs:(*int)(nil), EndpointReportingEnabled:(*bool)(nil), EndpointReportingDelaySecs:(*int)(nil), IptablesMarkMask:(*uint32)(nil), DisableConntrackInvalidCheck:(*bool)(nil), HealthEnabled:(*bool)(nil), HealthPort:(*int)(nil), PrometheusMetricsEnabled:(*bool)(nil), PrometheusMetricsPort:(*int)(nil), PrometheusGoMetricsEnabled:(*bool)(nil), PrometheusProcessMetricsEnabled:(*bool)(nil), FailsafeInboundHostPorts:(*[]v2.ProtoPort)(nil), FailsafeOutboundHostPorts:(*[]v2.ProtoPort)(nil), UsageReportingEnabled:(*bool)(nil), DebugMemoryProfilePath:"", DebugDisableLogDropping:(*bool)(nil), DebugSimulateCalcGraphHangAfterSecs:(*int)(nil), DebugSimulateDataplaneHangAfterSecs:(*int)(nil)}} error=Operation cannot be fulfilled on felixconfigurations.crd.projectcalico.org "default": the object has been modified; please apply your changes to the latest version and try again
2017-11-10 12:51:24.426 [ERROR][131] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 12:52:28.931 [ERROR][351] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 12:54:01.076 [ERROR][470] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 12:55:48.320 [ERROR][581] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 12:59:38.421 [ERROR][695] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:00:44.382 [ERROR][826] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:02:11.081 [ERROR][935] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:03:35.387 [ERROR][1045] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:05:26.780 [ERROR][1154] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:06:56.314 [ERROR][1265] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:08:40.279 [ERROR][1375] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:10:39.444 [ERROR][1487] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:11:45.234 [ERROR][1602] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:12:50.605 [ERROR][1710] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:14:49.290 [ERROR][1818] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:16:35.845 [ERROR][1932] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:18:35.037 [ERROR][2045] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:19:50.399 [ERROR][2159] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:21:04.284 [ERROR][2268] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:22:54.328 [ERROR][2377] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:24:08.470 [ERROR][2489] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:25:58.711 [ERROR][2599] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:27:25.497 [ERROR][2712] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:29:25.666 [ERROR][2822] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:31:13.548 [ERROR][2935] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:32:55.760 [ERROR][3049] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:34:52.815 [ERROR][3160] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:36:19.497 [ERROR][3273] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:37:31.856 [ERROR][3383] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:39:22.924 [ERROR][3491] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
2017-11-10 13:41:01.384 [ERROR][3603] networkpolicy.go 431: Resource returned from watch does not implement the ObjectMetaAccessor interface
```

**Comment by lwr20** [comment] 2017-11-10 13:43
Git commit hash (from Felix logs above) show that its the current felix master - and that appears to be using the latest libcalico-go master

**Comment by fasaxc** [comment] 2017-11-10 13:59
Looks like the problem is that 

- `networkPolicyWatcher` is trying to cast the value before it checks if there was an error.  
- It then bails out of the loop, closing the channel without sending on the terminating event, so the downstream watchercache gets an unexpected channel-close instead of a final event.
- The watchercache is supposed to handle that case, but it looks like there's a missing `continue` here:
```
		if !ok {
			// If the channel is closed then resync/recreate the watch.
			wc.logger.Info("Watch channel closed by remote - recreate watcher")
			wc.resyncAndCreateWatcher()
		}
```

**Closed** 2017-11-10 20:51 UTC
