### ISSUE TITLE
BlockPrefixLength configurable

### ISSUE THREAD

**Issue by peiqi-caicloud** [projectcalico/libcalico-go#903] opened 2018-07-11 05:54 UTC
Hello, 

can we make BlockPrefixLength configurable instead of fixing it as 26 ???

**Comment by caseydavenport** [comment] 2018-07-11 14:21
Closing as a duplicate of https://github.com/projectcalico/libcalico-go/issues/761

**Closed by caseydavenport** 2018-07-11 14:21 UTC
