### ISSUE TITLE
Update documentation to use new calicoctl commands

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#193] opened 2016-10-18 11:37 UTC
-  Update all of the docs to use the latest commands
-  Remove docs about non-docker networking docker containers
-  Update our vagrant demos
-  Move all documentation into the docs repo.

**Comment by caseydavenport** [comment] 2016-10-24 02:58
I think this is a duplicate of #194

**Closed by caseydavenport** 2016-10-24 02:58 UTC
