### ISSUE TITLE
Issue/Feature: Go mod release compliancy

### ISSUE THREAD

**Issue by svyotov** [projectcalico/libcalico-go#1342] opened 2020-11-12 10:23 UTC
This issue is an extension/addition to https://github.com/projectcalico/libcalico-go/issues/1305. 

https://github.com/projectcalico/libcalico-go uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release version is v3. And it’s module path is "github.com/projectcalico/libcalico-go", instead of "github.com/projectcalico/libcalico-go/v3". It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. 

`go mod` requires that project releases have a tag as well as the project `go.mod` file contains the major version of the release. This is simple to achieve, for example see https://github.com/projectcalico/calicoctl/pull/2223.

Similar issue to another calico project: https://github.com/projectcalico/calicoctl/issues/2126 with more details.

Quoting the specification:

>     A package that has opted in to modules must include the major version in the import path to import any v2+ modules
>     To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of example.com/m must instead use module path example.com/m/v2.
>     https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

## References

Identical issues: [[1]](https://github.com/projectcalico/calicoctl/issues/2126)
Sample changes required: [[1]](https://github.com/projectcalico/calicoctl/issues/2126)
Sample external open source projects: [[1]](https://github.com/go-git/go-git/blob/master/go.mod)
Relevant documentation: [[1]](https://github.com/golang/go/wiki/Modules#semantic-import-versioning)[[2]](https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning)[[3]](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher)

## Expected Behavior
```
> go get github.com/projectcalico/libcalico-go@v3.17.0
go: downloading github.com/projectcalico/libcalico-go v3.17.0
```
## Current Behavior
```
> go get github.com/projectcalico/libcalico-go@v3.17.0-0
go get github.com/projectcalico/libcalico-go@v3.17.0: github.com/projectcalico/libcalico-go@v3.17.0: invalid version: unknown revision v3.17.0
```
## Possible Solution
1. `git tag <semantic release>` && `git push origin <semantic release>` # on each release
2. Update the go.mod file with the version v3 as per this PR https://github.com/projectcalico/calicoctl/issues/2126

## Steps to Reproduce (for bugs)
Try to import this project in any normal `go mod` managed project.

## Context
Currently this forces me to manage this project dependency using hashes:
`go get github.com/projectcalico/libcalico-go@<git- hash>` instead of `go get github.com/projectcalico/libcalico-go@<release>`
which makes release mamangent and upgrades difficult and causes frequent dependencies breaks in my projects.

## Your Environment
* libcalico-go version: v3.17.0
* Operating System and version: Linux Fedora 33
* Link to your project (optional): primarily private for now

**Comment by caseydavenport** [comment] 2020-11-12 18:02
@svyotov thanks for the detailed issue! I believe that this is a duplicate of https://github.com/projectcalico/libcalico-go/issues/1305, so I would like to keep conversation in one place.

I commented on the calicoctl PR. I know that libcalico-go is way more of a gray area, since it is strongly implied to be a library :) 

However, I think the same logic more-or-less applies. At the moment, the Calico team does not guarantee that libcalico-go has any backward compatibility with previous versions. We don't cut releases of it, and my understanding is that following this pattern would be promising something to developers that just isn't true.

We can have the conversation about whether we should be changing libcalico to something that _is_ a supported, backward-compatible, released project, but that's not what it is right now.

Of course, I could be missing the point, so please let me know if I am :)

**Closed by caseydavenport** 2020-11-12 18:02 UTC

**Comment by svyotov** [comment] 2020-11-14 18:45
> Of course, I could be missing the point, so please let me know if I am :)

Releases make sense as even if new releases are not backwards compatible.
Using git hashes and with the current experience I have with `go mod` is not stable and very difficult to track.

To put it as simple as I can, it is just easier to know which release you are using (in communication and git diff) and it also means this is intended by the developers to be used and it is not a dev branch/hash. It also is compatible with golang versioning tools while hashes not so much.

**Comment by caseydavenport** [comment] 2020-11-16 18:31
> his is intended by the developers to be used and it is not a dev branch/hash.

Ah, I think this is where we disagree. The Calico team made a decision a while back that libcalico-go was _not_ intended to be for general use. Basically, we didn't have the resources to be in the business of supporting the libcalico-go API / library in addition to supporting end-users. 

To be honest, I would love to see a fully supported Calico golang library, but I don't think that libcalico-go is that thing. Right now it is more of a collection of arbitrary utilities and logic that is shared between Calico components. It just so happens that it is also where the important user-facing API structures are defined.

I'd prefer a `projectcalico/api` repository that has the struct definitions and clients, separate from the rest of the more "internal" logic that is libcalico-go. That is something I feel would be reasonable to version and release.
